### PR TITLE
Various features and fixes

### PR DESCRIPTION
**Pull request by Ocarthon**
While using phpunuhi for an internal project, i made some various changes to fit our needs. These range from bug fixes, performance improvements and features.

Feel free to comment on these changes, maybe you want to merge them into phpunuhi

Performance Improvement:
- [Lazily load snippets, when they are required](https://github.com/boxblinkracer/phpunuhi/commit/0269064d50d52bd0f40d27795ef381c9592fa8c4)
- [Index translations by id to reduce amount of loops over all translation keys](https://github.com/boxblinkracer/phpunuhi/commit/ac30b62afbb34122b4e0c8a2ed7dab92c9399797) (massive performance increase)

Bug fixes:
- [Save html export in set-specific files](https://github.com/boxblinkracer/phpunuhi/commit/3a3d62f5dc8515698d1a34b245414a9ab5fb31bf)
- [check all locales to determine the translation keys](https://github.com/boxblinkracer/phpunuhi/commit/1aa15ab8fc58092fdaa49875641e558bec41d8b6)
- [use mb collation for database collection](https://github.com/boxblinkracer/phpunuhi/commit/41234a94838faa64046bfc9a64b06c9047604a1c) (MySQL utf8 is not actually utf8)
- [fix: fix translate command with force flag](https://github.com/boxblinkracer/phpunuhi/commit/964155bcebf4a99bc113a4727842c9cfdc5ecd83)

Features:
- [support referencing snippets by their snippet set name](https://github.com/boxblinkracer/phpunuhi/commit/6318d98e8b9e610ea4e335412cfa53caa8f84bc7)
- [load dotenv files from current working directory](https://github.com/boxblinkracer/phpunuhi/commit/14224870f1c5c116cee57a462c71d7d722223e88)
- [allow deepl / translator configuration with env variables](https://github.com/boxblinkracer/phpunuhi/commit/0ffd4087488ee5afd98b8b77e88612993cdd037e)
- [enable deepl tag splitting on html input](https://github.com/boxblinkracer/phpunuhi/commit/9c97fd10b9b6f9f6958ed3c8d598e9a470865879)
- [insert shopware translation, if no corresponding row exists](https://github.com/boxblinkracer/phpunuhi/commit/1454063651eb2597985c2a48d97e5037bf1ba481)

### CODE REVIEW

**Comment by tmloberon** [comment]
With your code I have executed the commands below and there were no fatal errors!
Everything was done as it should.

- `phpunuhi translate --service=googelweb`
- `phpunuhi export  --dir exports  --empty --format=html`
- `phpunuhi import --file=import/XXX.csv --set=XXX`
- `phpunuhi validate:all`
- `phpunuhi fix:all`

**Comment by boxblinkracer** [comment]
Hi

wow this is amazing
i've just started the pipeline for you

ill check out the changes soon, thanks again for this :)

**Review by boxblinkracer — APPROVED** [review]

**Comment by boxblinkracer** [comment]
ok so i really like it, thank you sooo much
its still a draft but i guess i can merge it? @Ocarthon

**Comment by Ocarthon** [comment]
> ok so i really like it, thank you sooo much its still a draft but i guess i can merge it? @Ocarthon

Glad you like the changes :) I marked the PR as ready

**Pull request merged**
